# Generated by Django 3.0.8 on 2020-07-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='patient',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
