# Generated by Django 4.0.1 on 2022-01-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200720_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('id_card_number', models.CharField(max_length=100)),
                ('phone_number', models.CharField(db_index=True, max_length=30, null=True)),
                ('business_address', models.CharField(max_length=200, null=True)),
                ('is_local_people', models.CharField(max_length=20, null=True)),
                ('local_address', models.CharField(max_length=200, null=True)),
                ('anti_virus', models.CharField(max_length=20, null=True)),
                ('health_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('travel_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
